version: '3.8'

services:
  # Next.js Application
  menufy-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: menufy-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=${NEXTAUTH_URL:-https://your-domain.com}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - API_URL=${API_URL:-http://menufy-backend:9100}
      - API_WS_URL=${API_WS_URL:-http://menufy-backend:9002/ws}
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3000:3000"
    networks:
      - menufy-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: menufy-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - menufy-app
    networks:
      - menufy-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3



networks:
  menufy-network:
    driver: bridge

volumes:
  nginx-logs:
