version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: menufy_mongodb
    restart: always
    ports:
      - "5433:5433"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: menufy
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  mongo-data: