server:
  port: ${SERVER_PORT:9100}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:api-gateway}
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: authentication-service
          uri: ${AUTH_SERVICE_URL:http://127.0.0.1:9000}
          predicates:
            - Path=/login/**, /company/**, /table/**, /user/**
        - id: menu-service
          uri: ${MENU_SERVICE_URL:http://127.0.0.1:9001}
          predicates:
            - Path=/menu/**, /category/**, /item/**
        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://127.0.0.1:9002}
          predicates:
            - Path=/order/**, /ws/**
        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL:http://127.0.0.1:9003}
          predicates:
            - Path=/payment/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG