version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: menufy-mongodb
    ports:
        - "5433:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: menufy
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  mongo-data: