spring:
  kafka:
    bootstrap-servers: ${AUTH_SERVICE_KAFKA_URL:localhost:9092}
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:13.49.70.191}:${DB_PORT:5432}/${DB_NAME:menufy}
    schema: ${DB_SCHEMA:auth_service_schema}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:auth_service_schema}
server:
  port: ${SERVER_PORT:9000}
auth-service:
  auth-secret: ${AUTH_SERVICE_AUTH_SECRET:a80760fd40fe446efdb63087307211907f408cd188221009b37681d491b3672c}
  publisher: ${AUTH_SERVICE_AUTH_PUBLISHER:Menufy}
  guest-token-length: ${AUTH_SERVICE_GUEST_TOKEN_LENGTH:1000000000000}
  user-token-length: ${AUTH_SERVICE_USER_TOKEN_LENGTH:8640000000000}
  kafka:
    company-topic: ${AUTH_SERVICE_KAFKA_COMPANY_TOPIC:company}
    table-topic: ${AUTH_SERVICE_KAFKA_TABLE_TOPIC:table}